"""Regenerate pygments-notebook.css.

Run from anywhere with the site's venv:
    python assets/css/generate_pygments_notebook_css.py

Maps Pygments' lexer-level Python tokens onto VS Code's "Dark+" (default
dark theme) colors, for the embedded Jupyter notebooks' code cells
(nbconvert's --template basic emits the highlight spans but ships no CSS
for them at all).

Pygments is a pure lexer (regex-based), not a semantic analyzer like
Pylance -- it cannot tell a function *call* from a plain variable reference
(both are just Token.Name), so real VS Code semantic highlighting (which
does distinguish them) can't be fully replicated. This gets as close as a
lexer can: definitions, imports, builtins, self/cls, decorators, classes
are all distinguished; plain names (variables, parameters, attributes, AND
call-sites, indistinguishable at the lexer level) all get VS Code's
"variable" light blue (#9CDCFE).

Output is scoped under .jupyter-container and !important so it doesn't
collide with assets/css/style.scss's own (unscoped, !important) partial
Pygments-class overrides for the site's regular Rouge-highlighted markdown
code blocks -- both use the same Pygments-compatible class names
(.highlight .k, .n, etc.) since Rouge is Pygments-CSS-class-compatible by
design. Matches that file's "code blocks are always dark regardless of
site theme" convention, so no light-mode variant is needed here either.
"""
import re
from pathlib import Path

from pygments.style import Style
from pygments.token import (Token, Comment, Keyword, Name, String, Number,
                             Operator, Punctuation, Generic, Error)
from pygments.formatters import HtmlFormatter


class VSCodeDarkStyle(Style):
    background_color = "#1e1e1e"
    styles = {
        Token:               "#d4d4d4",
        Comment:             "italic #6a9955",
        Keyword:             "#c586c0",
        Keyword.Constant:    "#569cd6",
        Keyword.Namespace:   "#c586c0",
        Operator.Word:       "#c586c0",
        Name:                "#9cdcfe",
        Name.Function:       "#dcdcaa",
        Name.Function.Magic: "#dcdcaa",
        Name.Class:          "#4ec9b0",
        Name.Exception:      "#4ec9b0",
        Name.Namespace:      "#9cdcfe",
        Name.Builtin:        "#dcdcaa",
        Name.Builtin.Pseudo: "#9cdcfe italic",
        Name.Decorator:      "#dcdcaa",
        String:              "#ce9178",
        String.Escape:       "#d7ba7d",
        String.Interpol:     "#d4d4d4",
        Number:              "#b5cea8",
        Operator:            "#d4d4d4",
        Punctuation:         "#d4d4d4",
        Error:               "#f44747",
        Generic.Error:       "#f44747",
        Generic.Traceback:   "#f44747",
    }


SCOPE = '.jupyter-container .highlight'
OUT_PATH = Path(__file__).parent / 'pygments-notebook.css'

css = HtmlFormatter(style=VSCodeDarkStyle).get_style_defs(SCOPE)

# get_style_defs() also always emits a few generic, UNSCOPED helper rules for
# line-numbered code blocks (bare `pre { line-height: ... }`, `td.linenos`,
# `span.linenos`) that ignore the selector-prefix argument entirely. This
# notebook never uses line numbers, so they'd never match anything useful --
# but the bare `pre { ... !important }` would apply site-wide to every <pre>
# on every page, which is a real regression. Drop any line not actually
# scoped under .jupyter-container.
css = '\n'.join(line for line in css.splitlines() if SCOPE.split()[0] in line.split('{', 1)[0])

# Inject !important into every declaration so these rules win over
# style.scss's own !important rules for the classes it already styles
# (.jupyter-container .highlight .X has higher specificity than style.scss's
# bare .highlight .X, so !important vs !important resolves in our favor).
css = re.sub(r'([a-zA-Z-]+:\s*[^;{}]+?)(;|\s*(?=\}))', r'\1 !important\2', css)

header = (
    "/* Auto-generated by generate_pygments_notebook_css.py in this same\n"
    "   directory -- do not hand-edit; re-run that script instead. */\n\n"
)

OUT_PATH.write_text(header + css + '\n', encoding='utf-8', newline='\n')
print(f"Wrote {OUT_PATH} ({len(css.splitlines())} rules)")
